/**
 * Reason codes. Every rejection, pause and failure is expressed with one of these;
 * the UI and reports translate them, they never invent free-form verdicts.
 */
export const ReasonCode = {
  // data / providers
  DATA_REQUIREMENT_NOT_MET: "DATA_REQUIREMENT_NOT_MET",
  DATA_STALE: "DATA_STALE",
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
  NO_ROUTE: "NO_ROUTE",
  QUOTE_FIELD_MISSING: "QUOTE_FIELD_MISSING",
  QUOTE_SEMANTICS_UNRESOLVED: "QUOTE_SEMANTICS_UNRESOLVED",
  QUOTE_NOT_COMPARABLE: "QUOTE_NOT_COMPARABLE",
  QUOTE_STALE: "QUOTE_STALE",
  AMOUNT_UNIT_AMBIGUOUS: "AMOUNT_UNIT_AMBIGUOUS",
  UNKNOWN_VALUATION: "UNKNOWN_VALUATION",
  UNLIQUIDATABLE: "UNLIQUIDATABLE",
  RENT_UNKNOWN: "RENT_UNKNOWN",
  FX_MISSING: "FX_MISSING",

  // token filters
  TOKEN_AGE_OUT_OF_RANGE: "TOKEN_AGE_OUT_OF_RANGE",
  LIQUIDITY_TOO_LOW: "LIQUIDITY_TOO_LOW",
  VOLUME_5M_TOO_LOW: "VOLUME_5M_TOO_LOW",
  SELLS_5M_TOO_FEW: "SELLS_5M_TOO_FEW",
  HOLDERS_TOO_FEW: "HOLDERS_TOO_FEW",
  TOP10_CONCENTRATION_TOO_HIGH: "TOP10_CONCENTRATION_TOO_HIGH",
  LARGEST_HOLDER_TOO_HIGH: "LARGEST_HOLDER_TOO_HIGH",
  HOLDER_DATA_UNAVAILABLE: "HOLDER_DATA_UNAVAILABLE",
  PRICE_IMPACT_TOO_HIGH: "PRICE_IMPACT_TOO_HIGH",
  ROUND_TRIP_COST_TOO_HIGH: "ROUND_TRIP_COST_TOO_HIGH",
  PRICE_PUMP_5M_TOO_HIGH: "PRICE_PUMP_5M_TOO_HIGH",
  MINT_AUTHORITY_ACTIVE: "MINT_AUTHORITY_ACTIVE",
  FREEZE_AUTHORITY_ACTIVE: "FREEZE_AUTHORITY_ACTIVE",
  TOKEN_PROGRAM_UNSUPPORTED: "TOKEN_PROGRAM_UNSUPPORTED",
  TOKEN_EXTENSION_NOT_ALLOWED: "TOKEN_EXTENSION_NOT_ALLOWED",
  TOKEN_EXTENSION_UNKNOWN: "TOKEN_EXTENSION_UNKNOWN",
  MINT_DATA_INVALID: "MINT_DATA_INVALID",
  BASE_ASSET_NOT_TRADABLE: "BASE_ASSET_NOT_TRADABLE",
  PRE_MIGRATION_BONDING_CURVE: "PRE_MIGRATION_BONDING_CURVE",

  // signal
  CONFLUENCE_NOT_MET: "CONFLUENCE_NOT_MET",
  CLUSTER_UNKNOWN: "CLUSTER_UNKNOWN",
  SIGNAL_EXPIRED: "SIGNAL_EXPIRED",
  SIGNAL_EVENT_LATE: "SIGNAL_EVENT_LATE",
  WALLET_NOT_QUALIFIED: "WALLET_NOT_QUALIFIED",
  INSUFFICIENT_QUALIFIED_WALLETS: "INSUFFICIENT_QUALIFIED_WALLETS",

  // risk / limits
  NOTIONAL_BELOW_MINIMUM: "NOTIONAL_BELOW_MINIMUM",
  MAX_POSITIONS_REACHED: "MAX_POSITIONS_REACHED",
  EXPOSURE_LIMIT: "EXPOSURE_LIMIT",
  INSUFFICIENT_USDC: "INSUFFICIENT_USDC",
  INSUFFICIENT_SOL_RESERVE: "INSUFFICIENT_SOL_RESERVE",
  DAILY_ATTEMPT_LIMIT: "DAILY_ATTEMPT_LIMIT",
  DAILY_NOTIONAL_LIMIT: "DAILY_NOTIONAL_LIMIT",
  POSITION_ALREADY_OPEN: "POSITION_ALREADY_OPEN",
  UNRESOLVED_ORDER: "UNRESOLVED_ORDER",
  MINT_COOLDOWN: "MINT_COOLDOWN",
  DEPLOYER_GROUP_OVERLAP: "DEPLOYER_GROUP_OVERLAP",
  ENTRY_WINDOW_CLOSED: "ENTRY_WINDOW_CLOSED",
  SESSION_NOT_RUNNING: "SESSION_NOT_RUNNING",
  ENTRIES_PAUSED: "ENTRIES_PAUSED",
  FEE_CAP_EXCEEDED: "FEE_CAP_EXCEEDED",
  RENT_CAP_EXCEEDED: "RENT_CAP_EXCEEDED",
  DAILY_LOSS_TRIGGER: "DAILY_LOSS_TRIGGER",
  SESSION_LOSS_TRIGGER: "SESSION_LOSS_TRIGGER",
  DRAWDOWN_TRIGGER: "DRAWDOWN_TRIGGER",
  RECONCILIATION_MISMATCH: "RECONCILIATION_MISMATCH",

  // execution
  MIN_OUT_NOT_MET: "MIN_OUT_NOT_MET",
  MODELED_EXECUTION_FAILURE: "MODELED_EXECUTION_FAILURE",
  SAME_MINT_REQUIRED: "SAME_MINT_REQUIRED",

  // exits
  EXIT_POLICY_VIOLATION: "EXIT_POLICY_VIOLATION",
  EXIT_EMERGENCY: "EXIT_EMERGENCY",
  EXIT_STOP_LOSS: "EXIT_STOP_LOSS",
  EXIT_DISTRIBUTION: "EXIT_DISTRIBUTION",
  EXIT_TRAILING_STOP: "EXIT_TRAILING_STOP",
  EXIT_TAKE_PROFIT: "EXIT_TAKE_PROFIT",
  EXIT_TIME_STOP: "EXIT_TIME_STOP",
  EXIT_SESSION_END: "EXIT_SESSION_END",

  // configuration / safety
  SIGNER_SECRET_IN_PAPER: "SIGNER_SECRET_IN_PAPER",
  SEND_BLOCKED_BY_TRANSPORT: "SEND_BLOCKED_BY_TRANSPORT",
} as const;

export type ReasonCode = (typeof ReasonCode)[keyof typeof ReasonCode];

export interface Reason {
  code: ReasonCode;
  detail?: string;
  /** Observed vs. required values, always with units in the key names. */
  evidence?: Record<string, string | number | boolean | null>;
}

export function reason(code: ReasonCode, detail?: string, evidence?: Reason["evidence"]): Reason {
  const r: Reason = { code };
  if (detail !== undefined) r.detail = detail;
  if (evidence !== undefined) r.evidence = evidence;
  return r;
}
